apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
  labels:
    airshipit.org/ephemeral-node: "true"
    airshipit.org/deploy-k8s: "false"
  name: node02
spec:
  online: true
  bootMACAddress: 00:3b:8b:0c:ec:8b
  networkData:
    name: node02-network-data
    namespace: default
  bmc:
    address: redfish+https://localhost:8443/redfish/v1/Systems/air-ephemeral
    credentialsName: node02-bmc-secret
status:
  provisioning:
# we need this status to make sure, that the host is not going to be
# reprovisioned by the ephemeral baremetal operator.
# when we have more flexible labeling system in place, we will not
# deliver this document to ephemeral cluster
    state: externally provisioned
