# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- block:
  - name: Ensuring Libvirt, Qemu and support packages are present
    become: yes
    vars:
      - packages:
          Debian:
          - qemu
          - libvirt-bin
          - libguestfs-tools
          - qemu-kvm
          - python3-lxml
          - python3-libvirt
          - dnsmasq
          - ebtables
          RedHat:
          - libguestfs-tools
          - libvirt
          - libvirt-devel
          - libvirt-daemon-kvm
          - qemu-kvm
    package:
      name: "{{ packages[ansible_os_family] }}"
      state: present
  - name: Add user "{{ ansible_user }}" to libvirt group
    become: yes
    user:
      name: "{{ ansible_user }}"
      groups:
      - libvirt
      append: yes
  - name: Reset ssh connection to allow user changes to affect "{{ ansible_user }}"
    meta: reset_connection
    ignore_errors: true
  - name: Start libvirtd
    service:
      name: libvirtd
      state: started
      enabled: true
    become: yes

