apiVersion: airshipit.org/v1alpha1
kind: PhasePlan
metadata:
  name: phasePlan
description: "Default phase plan"
phases:
  - name: initinfra-ephemeral
  - name: initinfra-networking-ephemeral
  - name: clusterctl-init-ephemeral
  - name: controlplane-ephemeral
  - name: clusterctl-init-target
  - name: initinfra-target
  - name: initinfra-networking-target
  - name: workers-target
  - name: workload-target

---
apiVersion: airshipit.org/v1alpha1
kind: PhasePlan
metadata:
  name: iso
description: "Runs phases to build iso image"
phases:
  - name: iso-cloud-init-data
  - name: iso-build-image

