# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: set apache log dir
  set_fact:
    apache_log_dir: "{{ logs_dir }}/apache"

- name: ensure directory for apache logs exists
  file:
    state: directory
    path: "{{ apache_log_dir }}"

- name: dump apache logs to directory
  shell: |-
    journalctl --unit apache2.service > "{{ apache_log_dir }}/apache2-service.log"
  args:
    executable: /bin/bash
  ignore_errors: True
  become: true

- name: copy configs
  command: "cp -r /etc/apache2 {{ apache_log_dir }}/configs"
  become: true

- name: copy logs
  command: "cp -r /var/log/apache2 {{ apache_log_dir }}/logs"
  become: true

- name: Change ownership of the logs dir
  file:
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    path: "{{ apache_log_dir }}"
  become: true

- name: "Downloads logs to executor"
  synchronize:
    src: "{{ apache_log_dir }}"
    dest: "{{ zuul.executor.log_root }}/{{ inventory_hostname }}"
    mode: pull
  ignore_errors: True
