# These rules inject env vars into the ephemeral function.
apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: ephemeral-env-vars-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: localhost/replacement-transformer
replacements:
# Replace the proxy vars
- source:
    objref:
      name: env-vars-catalogue
    fieldref: env.HTTP_PROXY
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_HTTP_PROXY%"]
- source:
    objref:
      name: env-vars-catalogue
    fieldref: env.HTTPS_PROXY
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_HTTPS_PROXY%"]
- source:
    objref:
      name: env-vars-catalogue
    fieldref: env.NO_PROXY
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_NO_PROXY%"]
