# These rules inject networking info artifacts into the ephemeral function.
apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: ephemeral-networking-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:v2.0.2
replacements:
# Substring-replace the ephemeral control plane's info
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.kubernetes.controlPlaneEndpoint.host
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CP_IP%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.kubernetes.controlPlaneEndpoint.port
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CP_PORT%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.kubernetes.apiserverCertSANs
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CERT_SANS%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.kubernetes.podCidr
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_POD_CIDR%"]
