apiVersion: airshipit.org/v1alpha1
kind: ImageConfiguration
metadata:
  name: default
  labels:
    airshipit.org/deploy-k8s: "false"
builder:
  networkConfigFileName: network-config
  outputMetadataFileName: output-metadata.yaml
  userDataFileName: user-data
container:
  containerRuntime: docker
  image: quay.io/airshipit/isogen:latest-ubuntu_focal
  volume: /srv/iso:/config
